name: funny stuff lel
favicon: null
layout_spectrum: 0.4846942671574652
typography_spectrum: 0.45616203313693404
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.75
  lightness: 0.8931680261157453
  saturation: 0.9769547111354768
  rhythmicContrast: 0.35976275335997343
purpose: []
