name: funny stuff lel
favicon: null
layout_spectrum: 0.13209
typography_spectrum: 0.45616203313693404
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#c89b0e'
    - '#745a09'
    - '#939393'
    - '#383838'
  brandStrength: 0.5
  lightness: 0.8931680261157453
  saturation: 0.9769547111354768
  rhythmicContrast: 0.35976275335997343
purpose: []
